<?php
/**
 * Generate or verify the Worker subset of the authoritative PHP Anchors.
 */

require_once __DIR__ . '/../../src/Anchors.php';

$names = array(
    'WORKER_INTEGRATION_KEY_BYTES',
    'WORKER_CLOCK_SKEW_SECONDS',
    'WORKER_ENVELOPE_MAX_CHARS',
    'MANAGED_ID_MAX_CHARS',
    'WORKER_OPAQUE_MAX_CHARS',
    'MANAGED_FINALIZED_TTL_SECONDS',
    'WORKER_UPLOAD_RATE_LIMIT_REQUESTS',
    'WORKER_UPLOAD_RATE_LIMIT_PERIOD_SECONDS',
    'REVIEW_PREVIEW_MAX_EDGE',
    'REVIEW_PREVIEW_MAX_BYTES',
    'REVIEW_PREVIEW_JPEG_QUALITY_INITIAL',
);
$output = "// Generated by worker/scripts/sync-anchors.php from src/Anchors.php. Do not edit.\n";
foreach ( $names as $name ) {
    $output .= 'export const ' . $name . ' = ' . Anchors::get( $name ) . ";\n";
}

$config_path = __DIR__ . '/../wrangler.jsonc';
$config = is_file( $config_path ) ? json_decode( file_get_contents( $config_path ), true ) : null;
$rate_limit = is_array( $config ) && isset( $config['ratelimits'][0]['simple'] )
    ? $config['ratelimits'][0]['simple']
    : null;
if ( ! is_array( $rate_limit )
    || ! isset( $rate_limit['limit'], $rate_limit['period'] )
    || $rate_limit['limit'] !== Anchors::get( 'WORKER_UPLOAD_RATE_LIMIT_REQUESTS' )
    || $rate_limit['period'] !== Anchors::get( 'WORKER_UPLOAD_RATE_LIMIT_PERIOD_SECONDS' )
) {
    fwrite( STDERR, "Worker rate-limit binding is stale relative to src/Anchors.php.\n" );
    exit( 1 );
}

$target = __DIR__ . '/../src/anchors.js';
$check = isset( $argv[1] ) && $argv[1] === '--check';
if ( $check ) {
    $current = is_file( $target ) ? file_get_contents( $target ) : false;
    if ( ! is_string( $current ) || ! hash_equals( $output, $current ) ) {
        fwrite( STDERR, "Worker Anchors are stale; run php worker/scripts/sync-anchors.php.\n" );
        exit( 1 );
    }
    exit( 0 );
}

if ( file_put_contents( $target, $output, LOCK_EX ) !== strlen( $output ) ) {
    fwrite( STDERR, "Unable to write Worker Anchors.\n" );
    exit( 1 );
}
