// Generated by worker/scripts/sync-anchors.php from src/Anchors.php. Do not edit.
export const WORKER_INTEGRATION_KEY_BYTES = 32;
export const WORKER_CLOCK_SKEW_SECONDS = 120;
export const WORKER_ENVELOPE_MAX_CHARS = 4096;
export const MANAGED_ID_MAX_CHARS = 128;
export const WORKER_OPAQUE_MAX_CHARS = 128;
export const MANAGED_FINALIZED_TTL_SECONDS = 2592000;
export const WORKER_UPLOAD_RATE_LIMIT_REQUESTS = 6;
export const WORKER_UPLOAD_RATE_LIMIT_PERIOD_SECONDS = 60;
export const REVIEW_PREVIEW_MAX_EDGE = 1600;
export const REVIEW_PREVIEW_MAX_BYTES = 2097152;
export const REVIEW_PREVIEW_JPEG_QUALITY_INITIAL = 82;
