<?php
/**
 * Fixed runtime invariants.
 *
 * Fixed runtime bounds and constants for eForms.
 * Code MUST NOT parse documentation at runtime.
 *
 * If a fixed value changes, update the corresponding tests and docs in the same task.
 */

class Anchors
{
    /**
     * All fixed runtime bounds and constants.
     */
    const VALUES = array(
        'MIN_FILL_SECONDS_MIN' => 0,
        'MIN_FILL_SECONDS_MAX' => 60,
        'TOKEN_TTL_MIN' => 1,
        'TOKEN_TTL_MAX' => 86400,
        'MAX_FORM_AGE_MIN' => 1,
        'MAX_FORM_AGE_MAX' => 86400,
        'LEDGER_GC_GRACE_SECONDS' => 3600,
        'CHALLENGE_TIMEOUT_MIN' => 1,
        'CHALLENGE_TIMEOUT_MAX' => 5,
        'THROTTLE_MAX_PER_MIN_MIN' => 1,
        'THROTTLE_MAX_PER_MIN_MAX' => 120,
        'THROTTLE_COOLDOWN_MIN' => 0,
        'THROTTLE_COOLDOWN_MAX' => 600,
        'LOGGING_LEVEL_MIN' => 0,
        'LOGGING_LEVEL_MAX' => 2,
        'RETENTION_DAYS_MIN' => 1,
        'RETENTION_DAYS_MAX' => 365,
        'MAX_FIELDS_MIN' => 1,
        'MAX_FIELDS_MAX' => 1000,
        'MAX_OPTIONS_MIN' => 1,
        'MAX_OPTIONS_MAX' => 1000,
        'MAX_MULTIVALUE_MIN' => 1,
        'MAX_MULTIVALUE_MAX' => 1000,
        'DECLINED_REVIEW_ADMIN_DEFAULT_DAYS' => 7,
        'DECLINED_REVIEW_ADMIN_MAX_DAYS' => 31,
        'DECLINED_REVIEW_SCAN_MAX_RECORDS' => 5000,
        'DECLINED_REVIEW_PAGE_SIZE' => 25,
        'RETAINED_SUBMISSIONS_PAGE_SIZE' => 50,
        'RETAINED_SUBMISSIONS_SCAN_PAGE_SIZE' => 100,
        'SUBMISSION_REVIEW_SNAPSHOT_LABEL_MAX_BYTES' => 120,
        'SUBMISSION_REVIEW_SNAPSHOT_VALUE_MAX_BYTES' => 4096,
        'DECLINED_REVIEW_MAX_FIELDS' => 100,
        'DECLINED_REVIEW_FIELD_MAX_BYTES' => 4096,
        'DECLINED_REVIEW_RECORD_FIELDS_MAX_BYTES' => 65536,
        'CONTENT_FILTER_MAX_TERMS' => 100,
        'CONTENT_FILTER_MAX_TERM_CHARS' => 80,
        'RUNTIME_HEALTH_PROBE_ENTROPY_BYTES' => 8,
        'MANAGED_OBJECT_MAX_BYTES' => 53687091200,
        'MANAGED_UPLOAD_MIN_FREE_BYTES' => 10737418240,
        'MANAGED_RESERVATION_STALE_SECONDS' => 3600,
        'MANAGED_UPLOAD_INTENT_TTL_SECONDS' => 3600,
        'MANAGED_ORPHAN_CLEANUP_GRACE_SECONDS' => 3600,
        'MANAGED_STAGED_DELETE_GRACE_SECONDS' => 86400,
        'MANAGED_FINALIZED_TTL_SECONDS' => 2592000,
        'MANAGED_AVAILABILITY_30_DAYS_SECONDS' => 2592000,
        'MANAGED_AVAILABILITY_90_DAYS_SECONDS' => 7776000,
        'MANAGED_AVAILABILITY_1_YEAR_SECONDS' => 31536000,
        'MANAGED_SUBMISSION_UUID_BYTES' => 16,
        'MANAGED_REVIEW_TAG_BYTES' => 16,
        'MANAGED_BATCH_ID_CHARS' => 43,
        'MANAGED_ID_MAX_CHARS' => 128,
        'WORKER_OPAQUE_MAX_CHARS' => 128,
        'MANAGED_BATCH_SECRET_BYTES' => 32,
        'MANAGED_UPLOAD_ID_BYTES' => 16,
        'MANAGED_UPLOAD_CONCURRENCY' => 3,
        'STAGED_THROTTLED_REQUESTS_PER_BATCH' => 1,
        'STAGED_THROTTLED_REQUESTS_PER_ITEM' => 2,
        'MANAGED_DISPLAY_NAME_MAX_CHARS' => 128,
        'MANAGED_ARTIFACT_MAX_BYTES' => 18874368,
        'MANAGED_ARTIFACT_MAX_PIXELS' => 60000000,
        'MANAGED_ARTIFACT_MAX_EDGE' => 12000,
        'CLIENT_PREPARATION_RECIPE_VERSION' => 1,
        'CLIENT_PREPARATION_SLOTS' => 1,
        'CLIENT_PREPARATION_JPEG_TRIGGER_BYTES' => 4194304,
        'CLIENT_PREPARATION_JPEG_TRIGGER_EDGE' => 2560,
        'CLIENT_PREPARATION_INPUT_MAX_BYTES' => 25165824,
        'CLIENT_PREPARATION_INPUT_MAX_PIXELS' => 60000000,
        'CLIENT_PREPARATION_INPUT_MAX_EDGE' => 12000,
        'CLIENT_PREPARATION_OUTPUT_MAX_EDGE' => 2560,
        'CLIENT_PREPARATION_JPEG_QUALITY' => 82,
        'CLIENT_PREPARATION_MIN_SAVINGS_PERCENT' => 15,
        'CLIENT_PREPARATION_TIMEOUT_MS' => 15000,
        'CLIENT_PREPARATION_HEADER_SCAN_BYTES' => 524288,
        'CLIENT_PREPARATION_EXIF_MAX_ENTRIES' => 512,
        'MANAGED_IMAGE_CONTAINER_MAX_CHUNKS' => 4096,
        'MANAGED_HEIF_MAX_BOXES' => 4096,
        'MANAGED_HEIF_MAX_ASSOCIATION_ENTRIES' => 4096,
        'MANAGED_HEIF_MAX_ASSOCIATIONS' => 4096,
        'WORKER_INTEGRATION_KEY_BYTES' => 32,
        'WORKER_UPLOAD_GRANT_TTL_SECONDS' => 900,
        'WORKER_UPLOAD_MAX_SECONDS' => 1800,
        'WORKER_RECEIPT_TTL_SECONDS' => 900,
        'WORKER_SECONDARY_KEY_RETENTION_SECONDS' => 3600,
        'WORKER_REVIEW_GRANT_TTL_SECONDS' => 300,
        'WORKER_OPERATION_GRANT_TTL_SECONDS' => 60,
        'WORKER_CLOCK_SKEW_SECONDS' => 120,
        'WORKER_ENVELOPE_MAX_CHARS' => 4096,
        'WORKER_RESPONSE_MAX_BYTES' => 8192,
        'WORKER_SERVER_REQUEST_TIMEOUT_SECONDS' => 10,
        'WORKER_LATENCY_FAST_MAX_MS' => 100,
        'WORKER_LATENCY_NORMAL_MAX_MS' => 1000,
        'WORKER_LATENCY_SLOW_MAX_MS' => 5000,
        'WORKER_UPLOAD_RATE_LIMIT_REQUESTS' => 6,
        'WORKER_UPLOAD_RATE_LIMIT_PERIOD_SECONDS' => 60,
        'MANAGED_LIFECYCLE_SAFETY_MARGIN_SECONDS' => 604800,
        'MANAGED_REMOTE_PURGE_AGGREGATE_PAGE_SIZE' => 25,
        'R2_LIFECYCLE_RESPONSE_MAX_BYTES' => 1048576,
        'R2_LIFECYCLE_REQUEST_TIMEOUT_SECONDS' => 15,
        'LOCAL_PREVIEW_CONCURRENCY_MAX' => 2,
        'LOCAL_PREVIEW_RETRY_AFTER_SECONDS' => 2,
        'LOCAL_PREVIEW_MIN_MEMORY_BYTES' => 805306368,
        'LOCAL_PREVIEW_MIN_EXECUTION_SECONDS' => 60,
        'REVIEW_PREVIEW_LOAD_TIMEOUT_MS' => 30000,
        'REVIEW_PREVIEW_MAX_EDGE' => 1600,
        'REVIEW_PREVIEW_MAX_BYTES' => 2097152,
        'REVIEW_PREVIEW_JPEG_QUALITY_INITIAL' => 82,
        'REVIEW_PREVIEW_JPEG_QUALITY_STEP' => 4,
        'REVIEW_PREVIEW_EDGE_STEP' => 160,
        'REVIEW_PREVIEW_MAX_ATTEMPTS' => 5,
        'STAGED_MULTIPART_OVERHEAD_BYTES' => 1048576,
    );

    /**
     * Get a fixed runtime value by name.
     *
     * @param string $name Value name (e.g., 'TOKEN_TTL_MAX').
     * @return int|null The value, or null if not found.
     */
    public static function get($name)
    {
        if (isset(self::VALUES[$name])) {
            return self::VALUES[$name];
        }

        // Warn in dev mode so typos are caught early.
        if (defined('WP_DEBUG') && WP_DEBUG) {
            trigger_error("Unknown anchor: $name", E_USER_WARNING);
        }

        return null;
    }
}
